apiVersion: apps/v1
kind: Deployment
metadata:
  name: sub2-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: sub2-app
  template:
    metadata:
      labels:
        app: sub2-app
    spec:
      containers:
        - name: sub2-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - name: http
              containerPort: 3000
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
