replicaCount: 1

image:
  repository: sigigi/k8s-monitoring-test-app
  tag: main-app-latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3000"
    prometheus.io/path: "/metrics"

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

podLabels:
  app.kubernetes.io/name: main-app
  app.kubernetes.io/instance: main-app
  prometheus: enabled