apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: main-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/sigigi/k8s-monitoring-test-app.git'
    targetRevision: HEAD
    path: apps/main-app/helm/main-app
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: project-test-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
